spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowercase-service-id: true
    httpclient:
      connect-timeout: 1000
      response-timeout: 5s
  data:
    redis:
      connect-timeout: 1000
      host: "localhost"
      port: 6379
      timeout: 1s
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: gatewayserver
    description: "My Bank Gateway server Application"
    version: "1.0.0"

logging:
  level:
    com:
      myBank:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  config:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 1000
      timeoutDuration: 20000ms